import {expect, test} from '@playwright/test';
import {HuntApp} from './pages';

/**
 * E2E test for "Le Secret du Vieux-Lille" application.
 *
 * This test simulates a complete user journey from app initialization
 * to the final place discovery, going through all the places in the game.
 *
 * This test has been automatically generated by Copilot with Claude Sonnet 4.5 from a detailed scenario.
 */
test.describe('Le Secret du Vieux-Lille', () => {

  test('Complete user journey from start to final place discovery', async ({ page }) => {
    // Configuration for CI stability
    test.setTimeout(300000); // 5 minutes — covers slow Mobile Safari iPhone 15 in CI

    // Initialize the Hunt App
    const app = new HuntApp(page);

    // ========================================
    // STEP 1: Application initialization
    // ========================================
    await test.step('Initialize application and authenticate with password', async () => {
      await app.navigateAndAuthenticate('/le-secret-du-vieux-lille');
      await app.verifyHuntTitle('Le Secret du Vieux-Lille');
    });

    // ========================================
    // STEP 2: Read manuscript and game rules
    // ========================================
    await test.step('Read manuscript and game rules', async () => {
      await app.manuscript.navigateToManuscript();
      await app.manuscript.verifyTabActive();
      await app.manuscript.verifyText('Le secret ···· ······················ se trouve ···· ········ ···· ···· ·············· ···· ···· ············');
      await app.manuscript.verifyClues('BRAS', 'OR');
    });

    // ========================================
    // STEP 3: Navigate to map tab
    // ========================================
    await test.step('Navigate to map tab', async () => {
      await app.map.navigateToMap();
      await app.map.verifyTabActive();

      // Wait for Google Maps to load
      await page.waitForTimeout(2000);

      // Verify search field presence
      await expect(app.map.searchField).toBeVisible({ timeout: 10000 });

      // Verify a marker is already present
      await app.map.verifyMarkerCount(1);
      await page.locator('.leaflet-marker-icon').first().click();
      await expect(app.map.popup).toBeVisible({ timeout: 10000 });
    });

    // ========================================
    // STEP 4: Place 1 - Le Bras d'Or
    // ========================================
    await test.step('Place 1: Le Bras d\'Or - Find first keyword "pied"', async () => {
      await app.map.closeAllModals();

      // The first place should already be displayed
      await app.map.verifyPopupPlace('Le Bras d\'Or');
      await app.map.showClue();

      // Solve the clickable image puzzle
      const clue = app.createClickableImageClue();

      // First click on the puzzle area to view the image
      await clue.viewImageInArea(0.9, 0.5, 'press.jpg');

      // Then solve by clicking the keyword
      await clue.solveAndClose();

      // Verify the phrase
      await app.manuscript.navigateToManuscript();
      await app.manuscript.verifyText('Le secret ···· ······················ se trouve ···· pied ···· ···· ·············· ···· ···· ············');
      await app.map.navigateToMap();
    });

    // ========================================
    // STEP 5: Place 2 - Musée de l'Hospice Comtesse
    // ========================================
    await test.step('Place 2: Musée de l\'Hospice Comtesse - View puzzle and find keyword "du"', async () => {
      await app.solveClickableImageWithPuzzle(
        'Hospice Comtesse',
        'Musée de l\'Hospice Comtesse',
        2,
        0.9,  // Top-right corner (x: right side)
        0.1,  // Top-right corner (y: top side)
        'code.jpg',  // Expected puzzle image
        'Le secret du ······················ se trouve ···· pied ···· ···· ·············· ···· ···· ············'
      );
    });

    // ========================================
    // STEP 6: Place 3 - Aux Merveilleux de Fred
    // ========================================
    await test.step('Place 3: Aux Merveilleux de Fred - Find keyword "Colonne" (scratch card)', async () => {
      await app.solveScratchCardPlace(
        'Aux Merveilleux de Fred Vieux Lille',
        'Aux Merveilleux de Fred',
        3,
        'Colonne',
        'Le secret du ······················ se trouve ···· pied ···· ···· Colonne ···· ···· ············',
        'Place aux Oignons'
      );
    });

    // ========================================
    // STEP 7: Place 4 - Place aux Oignons
    // ========================================
    await test.step('Place 4: Place aux Oignons - Find keyword "au"', async () => {
      await app.map.closeAllModals();
      await app.map.findPlace('Place aux Oignons', 'Place aux Oignons', 4);
      await app.map.showClue();

      const clue = app.createClickableImageClue();

      // First click on the card-flip area to view it
      await clue.clickArea(0.1, 0.78);
      await page.waitForTimeout(1000);

      // Click on the card image to flip it and reveal the hidden image on the back
      const cardFlipModal = page.locator('[data-testid="modal"]').nth(1);
      await expect(cardFlipModal).toBeVisible({ timeout: 5000 });
      const cardImage = cardFlipModal.locator('img').first();
      await expect(cardImage).toBeVisible({ timeout: 2000 });

      // Click in the top-right corner of the card to flip it
      const imageBox = await cardImage.boundingBox();
      if (imageBox) {
        const clickX = imageBox.x + imageBox.width * 0.9; // Top-right corner
        const clickY = imageBox.y + imageBox.height * 0.1;
        await page.mouse.click(clickX, clickY);
        await page.waitForTimeout(1000); // Wait for flip animation
      }

      // Close the card-flip modal
      const closeButton = cardFlipModal.getByTestId('modal-close');
      await closeButton.click();
      await page.waitForTimeout(500);

      // Then solve by clicking the keyword
      await clue.solveAndClose();

      await app.manuscript.navigateToManuscript();
      await app.manuscript.verifyText('Le secret du ······················ se trouve au pied ···· ···· Colonne ···· ···· ············');
      await app.map.navigateToMap();
    });

    // ========================================
    // STEP 8: Place 5 - Cathédrale Notre-Dame-de-la-Treille
    // ========================================
    await test.step('Place 5: Cathédrale Notre-Dame-de-la-Treille - Find keyword "la"', async () => {
      await app.map.closeAllModals();
      await app.map.findPlace('Notre Dame de la Treille', 'Cathédrale Notre-Dame-de-la-Treille', 5);
      await app.map.showClue();

      const clue = app.createClickableImageClue();

      // First click on the letter/image area to view it
      await clue.viewImageInArea(0.95, 0.55, 'letter.png');

      // Then solve by clicking the keyword
      await clue.solveAndClose();

      await app.manuscript.navigateToManuscript();
      await app.manuscript.verifyText('Le secret du ······················ se trouve au pied ···· la Colonne ···· la ············');
      await app.map.navigateToMap();
    });

    // ========================================
    // STEP 9: Place 6 - Maison Méert
    // ========================================
    await test.step('Place 6: Maison Méert - Find keyword "de" (3D box)', async () => {
      await app.solveBox3DPlace(
        'Maison Meert',
        'Maison Méert',
        6,
        'Le secret du ······················ se trouve au pied de la Colonne de la ············'
      );
    });

    // ========================================
    // STEP 10: Place 7 - Vieille Bourse
    // ========================================
    await test.step('Place 7: Vieille Bourse - Find keyword "Vieux-Lille" (page flip)', async () => {
      await app.solvePageFlipPlace(
        'Vieille Bourse',
        'Vieille Bourse',
        7,
        'Le secret du Vieux-Lille se trouve au pied de la Colonne de la ············',
        'Opéra de Lille'
      );
    });

    // ========================================
    // STEP 11: Place 8 - Opéra de Lille
    // ========================================
    await test.step('Place 8: Opéra de Lille - Find keyword "Déesse" (magnifier)', async () => {
      await app.solveMagnifierPlace(
        'Opera de Lille',
        'Opéra de Lille',
        8,
        'Le secret du Vieux-Lille se trouve au pied de la Colonne de la Déesse'
      );
    });

    // ========================================
    // STEP 12: Verify complete phrase is revealed
    // ========================================
    await test.step('Verify complete phrase is revealed', async () => {
      await app.manuscript.navigateToManuscript();
      await app.manuscript.verifyText('Le secret du Vieux-Lille se trouve au pied de la Colonne de la Déesse');
      await app.manuscript.verifyPhraseComplete();
    });

    // ========================================
    // STEP 13: Final place - Colonne de la Déesse
    // ========================================
    await test.step('Final place: Colonne de la Déesse - Discover the last place location', async () => {
      await app.verifyTreasureLocation(
        'Colonne de la Deesse',
        'Colonne de la Déesse',
        9,
        'FÉLICITATIONS',
        'Vous avez trouvé le secret du Vieux-Lille'
      );
    });

    // ========================================
    // STEP 14: Data persistence test
    // ========================================
    await test.step('Verify data persistence after reload', async () => {
      await app.verifyPersistence(9, 'Le secret du Vieux-Lille se trouve au pied de la Colonne de la Déesse');
    });
  });
});
