import {expect, test} from '@playwright/test';
import {HuntApp} from './pages';

/**
 * E2E test for "Le Trésor du Vieux-Lille" application.
 *
 * This test simulates a complete user journey from app initialization
 * to the final treasure discovery, going through all the places in the game.
 *
 * This test has been automatically generated by Copilot with Claude Sonnet 4.5 from a detailed scenario.
 */
test.describe('Le Trésor du Vieux-Lille', () => {

  test('Complete user journey from start to treasure discovery', async ({ page }) => {
    // Configuration for CI stability
    test.setTimeout(180000); // 3 minutes timeout for complete test

    // Initialize the Hunt App
    const app = new HuntApp(page);

    // ========================================
    // STEP 1: Application initialization
    // ========================================
    await test.step('Initialize application and authenticate with password', async () => {
      await app.navigateAndAuthenticate('/le-tresor-du-vieux-lille');
      await app.verifyHuntTitle('Le Trésor du Vieux-Lille');
    });

    // ========================================
    // STEP 2: Read manuscript and game rules
    // ========================================
    await test.step('Read manuscript and game rules', async () => {
      await app.manuscript.navigateToManuscript();
      await app.manuscript.verifyTabActive();
      await app.manuscript.verifyText('Le trésor ···· ······················ se trouve ···· ········ ···· ···· ·············· ···· ···· ············');
      await app.manuscript.verifyClues('BRAS', 'OR');
    });

    // ========================================
    // STEP 3: Navigate to map tab
    // ========================================
    await test.step('Navigate to map tab', async () => {
      await app.map.navigateToMap();
      await app.map.verifyTabActive();

      // Wait for Google Maps to load
      await page.waitForTimeout(2000);

      // Verify search field presence
      await expect(app.map.searchField).toBeVisible({ timeout: 10000 });

      // Verify a marker is already present
      await app.map.verifyMarkerCount(1);
      await expect(app.map.infoWindow).toBeVisible({ timeout: 10000 });
    });

    // ========================================
    // STEP 4: Place 1 - Le Bras d'Or
    // ========================================
    await test.step('Place 1: Le Bras d\'Or - Find first keyword "pied"', async () => {
      await app.map.closeAllModals();

      // The first place should already be displayed
      await app.map.verifyInfoWindowPlace('Le Bras d\'Or');
      await app.map.showClue();

      // Solve the clickable image puzzle
      const clue = app.createClickableImageClue();
      await clue.solveAndClose(/Bravo ! Vous avez trouvé un mot-clé vous menant vers le trésor !|Congratulations! You found a keyword leading to the treasure!|¡Felicidades! ¡Encontraste una palabra clave que conduce al tesoro!|Glückwunsch! Sie haben ein Schlüsselwort gefunden, das zum Schatz führt!|Gefeliciteerd! Je hebt een trefwoord gevonden dat naar de schat leidt!/);

      // Verify the phrase
      await app.manuscript.navigateToManuscript();
      await app.manuscript.verifyText('Le trésor ···· ······················ se trouve ···· pied ···· ···· ·············· ···· ···· ············');
      await app.map.navigateToMap();
    });

    // ========================================
    // STEP 5: Place 2 - Musée de l'Hospice Comtesse
    // ========================================
    await test.step('Place 2: Musée de l\'Hospice Comtesse - Find keyword "du"', async () => {
      await app.solveClickableImagePlace(
        'Hospice Comtesse',
        'Musée de l\'Hospice Comtesse',
        2,
        'Le trésor du ······················ se trouve ···· pied ···· ···· ·············· ···· ···· ············'
      );
    });

    // ========================================
    // STEP 6: Place 3 - Aux Merveilleux de Fred
    // ========================================
    await test.step('Place 3: Aux Merveilleux de Fred - Find keyword "Colonne" (scratch card)', async () => {
      await app.solveScratchCardPlace(
        'Aux Merveilleux de Fred Vieux Lille',
        'Aux Merveilleux de Fred',
        3,
        'Colonne',
        'Le trésor du ······················ se trouve ···· pied ···· ···· Colonne ···· ···· ············',
        'Place aux Oignons'
      );
    });

    // ========================================
    // STEP 7: Place 4 - Place aux Oignons
    // ========================================
    await test.step('Place 4: Place aux Oignons - Find keyword "au"', async () => {
      await app.solveClickableImagePlace(
        'Place aux Oignons',
        'Place aux Oignons',
        4,
        'Le trésor du ······················ se trouve au pied ···· ···· Colonne ···· ···· ············'
      );
    });

    // ========================================
    // STEP 8: Place 5 - Cathédrale Notre-Dame-de-la-Treille
    // ========================================
    await test.step('Place 5: Cathédrale Notre-Dame-de-la-Treille - Find keyword "la"', async () => {
      await app.solveClickableImagePlace(
        'Notre Dame de la Treille',
        'Cathédrale Notre-Dame-de-la-Treille',
        5,
        'Le trésor du ······················ se trouve au pied ···· la Colonne ···· la ············'
      );
    });

    // ========================================
    // STEP 9: Place 6 - Maison Méert
    // ========================================
    await test.step('Place 6: Maison Méert - Find keyword "de" (3D box)', async () => {
      await app.solveBox3DPlace(
        'Maison Meert',
        'Maison Méert',
        6,
        'Le trésor du ······················ se trouve au pied de la Colonne de la ············'
      );
    });

    // ========================================
    // STEP 10: Place 7 - Vieille Bourse
    // ========================================
    await test.step('Place 7: Vieille Bourse - Find keyword "Vieux-Lille" (page flip)', async () => {
      await app.solvePageFlipPlace(
        'Vieille Bourse',
        'Vieille Bourse',
        7,
        'Le trésor du Vieux-Lille se trouve au pied de la Colonne de la ············',
        'Opéra de Lille'
      );
    });

    // ========================================
    // STEP 11: Place 8 - Opéra de Lille
    // ========================================
    await test.step('Place 8: Opéra de Lille - Find keyword "Déesse" (magnifier)', async () => {
      await app.solveMagnifierPlace(
        'Opera de Lille',
        'Opéra de Lille',
        8,
        'Le trésor du Vieux-Lille se trouve au pied de la Colonne de la Déesse',
        'Félicitations ! Vous avez trouvé tous les mots cachés. Consultez la phrase pour découvrir le lieu du trésor !'
      );
    });

    // ========================================
    // STEP 12: Verify complete phrase is revealed
    // ========================================
    await test.step('Verify complete phrase is revealed', async () => {
      await app.manuscript.navigateToManuscript();
      await app.manuscript.verifyText('Le trésor du Vieux-Lille se trouve au pied de la Colonne de la Déesse');
      await app.manuscript.verifyPhraseComplete();
    });

    // ========================================
    // STEP 13: Final place - Colonne de la Déesse
    // ========================================
    await test.step('Final place: Colonne de la Déesse - Discover the treasure', async () => {
      await app.verifyTreasureLocation(
        'Colonne de la Deesse',
        'Colonne de la Déesse',
        9,
        'FÉLICITATIONS',
        'Vous avez trouvé le trésor du Vieux-Lille'
      );
    });

    // ========================================
    // STEP 14: Data persistence test
    // ========================================
    await test.step('Verify data persistence after reload', async () => {
      await app.verifyPersistence(9, 'Le trésor du Vieux-Lille se trouve au pied de la Colonne de la Déesse');
    });
  });
});
